// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BookmarkList from "./BookmarkList.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: "justify-center flex"
            }, React.createElement(BookmarkList.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
