// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Bookmark from "./Bookmark.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* New */0 :
        var href = action._1;
        if (Belt_Array.keep(state, (function (bookmark) {
                  return bookmark.href === href;
                })).length === 0) {
          return Belt_Array.concat(state, [{
                        title: action._0,
                        href: href,
                        tags: action._2
                      }]);
        } else {
          return state;
        }
    case /* Delete */1 :
        var href$1 = action._0;
        return Belt_Array.keep(state, (function (bookmark) {
                      return bookmark.href !== href$1;
                    }));
    case /* Update */2 :
        var tags = action._3;
        var newHref = action._2;
        var title = action._1;
        var oldHref = action._0;
        return Belt_Array.map(state, (function (bookmark) {
                      if (bookmark.href === oldHref) {
                        return {
                                title: title,
                                href: newHref,
                                tags: tags
                              };
                      } else {
                        return bookmark;
                      }
                    }));
    
  }
}

var initialState = [
  {
    title: "Neil Parikh",
    href: "https://www.neilparikh.me",
    tags: [
      "home",
      "neil",
      "anotherTag",
      "yetOneMore",
      "anotherTag2",
      "yetOneMore2"
    ]
  },
  {
    title: "Github",
    href: "https://github.com",
    tags: [
      "code",
      "social"
    ]
  }
];

function BookmarkList(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  return React.createElement("div", {
              className: "md:flex py-8 lg:px-8 lg:w-1/2 flex-col space-y-2 divide-y-4 divide-gray-300"
            }, Belt_Array.map(match[0], (function (bookmark) {
                    return React.createElement(Bookmark.make, {
                                title: bookmark.title,
                                href: bookmark.href,
                                tags: bookmark.tags,
                                onDelete: (function (param) {
                                    return Curry._1(dispatch, {
                                                TAG: /* Delete */1,
                                                _0: bookmark.href
                                              });
                                  }),
                                onEdit: (function (title, href, tags) {
                                    return Curry._1(dispatch, {
                                                TAG: /* Update */2,
                                                _0: bookmark.href,
                                                _1: title,
                                                _2: href,
                                                _3: tags
                                              });
                                  }),
                                key: bookmark.href
                              });
                  })));
}

var make = BookmarkList;

export {
  reducer ,
  initialState ,
  make ,
  
}
/* react Not a pure module */
