// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import TrashIcon from "@heroicons/react/solid/TrashIcon";
import PencilIcon from "@heroicons/react/solid/PencilIcon";

function Bookmark$Tag(Props) {
  var tagName = Props.tagName;
  return React.createElement("a", {
              key: tagName,
              className: "text-yellow-600",
              href: "/t:" + tagName
            }, tagName);
}

var Tag = {
  make: Bookmark$Tag
};

function Bookmark(Props) {
  var title = Props.title;
  var href = Props.href;
  var tags = Props.tags;
  var onDelete = Props.onDelete;
  var onEdit = Props.onEdit;
  var match = React.useState(function () {
        return {
                editing: false,
                title: title,
                href: href
              };
      });
  var setEditorState = match[1];
  var editorState = match[0];
  var editingClass = editorState.editing ? "text-red-600" : "text-green-600";
  var onEditClick = function (param) {
    return Curry._1(setEditorState, (function (prev) {
                  if (prev.editing) {
                    Curry._3(onEdit, prev.title, prev.href, tags);
                    return {
                            editing: false,
                            title: prev.title,
                            href: prev.href
                          };
                  } else {
                    return {
                            editing: true,
                            title: prev.title,
                            href: prev.href
                          };
                  }
                }));
  };
  return React.createElement("div", {
              className: "p-4 lg:width-1/2 flex flex-row space-x-4"
            }, React.createElement("div", {
                  className: "flex flex-col space-y-2"
                }, React.createElement(PencilIcon, {
                      className: "h-6 w-6 fill-current " + editingClass,
                      onClick: onEditClick
                    }), React.createElement(TrashIcon, {
                      className: "h-6 w-6 fill-current",
                      onClick: onDelete
                    })), React.createElement("div", {
                  className: "flex flex-col"
                }, editorState.editing ? React.createElement("input", {
                        className: "border-2",
                        type: "text",
                        value: editorState.title,
                        onChange: (function (e) {
                            return Curry._1(setEditorState, (function (prev) {
                                          return {
                                                  editing: prev.editing,
                                                  title: e.target.value,
                                                  href: prev.href
                                                };
                                        }));
                          })
                      }) : React.createElement("a", {
                        className: "text-blue-500 border-2 border-transparent",
                        href: href
                      }, title), editorState.editing ? React.createElement("input", {
                        className: "border-2",
                        type: "text",
                        value: editorState.href,
                        onChange: (function (e) {
                            return Curry._1(setEditorState, (function (prev) {
                                          return {
                                                  editing: prev.editing,
                                                  title: prev.title,
                                                  href: e.target.value
                                                };
                                        }));
                          })
                      }) : React.createElement("a", {
                        className: "text-gray-500 border-2 border-transparent",
                        href: href
                      }, href), React.createElement("div", {
                      className: "flex space-x-2 flex-wrap"
                    }, Belt_Array.map(tags, (function (tag) {
                            return React.createElement(Bookmark$Tag, {
                                        tagName: tag,
                                        key: tag
                                      });
                          })))));
}

var make = Bookmark;

export {
  Tag ,
  make ,
  
}
/* react Not a pure module */
